FROM python:3.10-slim

WORKDIR /app

# install only what your scripts need
RUN pip install --no-cache-dir kafka-python minio requests

# copy your code (includes weather_producer.py and weather_processor.py)
COPY . .

CMD ["python", "weather_producer.py"]
